In [ ]:
!pip install -U numpy pandas plotnine

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.0)
Requirement already satisfied: plotnine in /usr/local/lib/python3.10/dist-packages (0.12.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: matplotlib>=3.6.0 in /usr/local/lib/python3.10/dist-packages (from plotnine) (3.7.1)
Requirement already satisfied: mizani<0.10.0,>0.9.0 in /usr/local/lib/python3.10/dist-packages (from plotnine) (0.9.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from plotnine) (0.5.6)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from plotnine) (1.11.4)
Requirement already satisfied: statsmodels>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from plotnine) (0.14.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->plotnine) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->plotnine) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->plotnine) (4.47.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->plotnine) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->plotnine) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->plotnine) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6.0->plotnine) (3.1.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->plotnine) (1.16.0)

# Week 02 Assignment

In this assignment, you will be working with data and managing categorical variables and the categories/labels of the categorical variables.

1. Import the package pandas as pd and numpy as np.

In [ ]:
import plotnine

import numpy as np
import pandas as pd

## NCBirths dataset

2. Execute the cell below to download and import the dataset NCBirths from Dr. Donatello's webpage.  Read about the dataset on the [metadata webpage](https://www.norcalbiostat.com/data/ncbirthscodebook) for this dataset.

In [ ]:
ncbirths = pd.read_csv("https://www.norcalbiostat.com/data/NCbirths.csv")

In [ ]:
ncbirths

,fage,mage,mature,weeks,premie,visits,marital,gained,weight,lowbirthweight,gender,habit,whitemom
0,NaN,13,younger mom,39.0,full term,10.0,married,38.0,7.63,not low,male,nonsmoker,not white
1,NaN,14,younger mom,42.0,full term,15.0,married,20.0,7.88,not low,male,nonsmoker,not white
2,19.0,15,younger mom,37.0,full term,11.0,married,38.0,6.63,not low,female,nonsmoker,white
3,21.0,15,younger mom,41.0,full term,6.0,married,34.0,8.00,not low,male,nonsmoker,white
4,NaN,15,younger mom,39.0,full term,9.0,married,27.0,6.38,not low,female,nonsmoker,not white
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,47.0,42,mature mom,40.0,full term,10.0,not married,26.0,8.44,not low,male,nonsmoker,not white
996,34.0,42,mature mom,38.0,full term,18.0,not married,20.0,6.19,not low,female,nonsmoker,white
997,39.0,45,mature mom,40.0,full term,15.0,not married,32.0,6.94,not low,female,nonsmoker,white
998,55.0,46,mature mom,31.0,premie,8.0,not married,25.0,4.56,low,female,nonsmoker,not white
999,45.0,50,mature mom,39.0,full term,14.0,not married,23.0,7.13,not low,female,nonsmoker,white

3. Calculate the mean age of the mothers using the variable `mage`.

In [ ]:
np.mean(ncbirths["mage"])

27.0

4. Pregnancies last on average 38 weeks. Recode the `weeks` variable to change all records where `weeks` is greater than 38, to equal 38. That is, for all record where `weeks>38`, change the value of `weeks` to `= 38`.

In [ ]:
idx = ncbirths["weeks"] >= 38
ncbirths.loc[idx, "weeks"] = 38

In [ ]:
idx

0       True
1       True
2      False
3       True
4       True
       ...
995     True
996     True
997     True
998    False
999     True
Name: weeks, Length: 1000, dtype: bool

5. Use the property `.isna()` function to create a new variable called `missing_gained` on the `ncbirths` data set that identifies if data on the `gained` variable is missing.

In [ ]:
ncbirths["missing_gained"] = ncbirths["gained"].isna()
ncbirths["missing_gained"]

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: missing_gained, Length: 1000, dtype: bool

6. What percent of records are missing data on weight gained during pregnancy? There are several ways you can calculate this. Explain what your process, and answer the question in a full sentence.

In [ ]:
missing_percent = (ncbirths["gained"].isna().sum() / ncbirths.shape[0]) * 100 # EAR .sum() Nice
# EAR nothing wrong with the parentheses you added, but 27 / 1000 * 100 will evaluate just the same,
# since Python treats both / and * as the same precedence and works left 27/1000 to right (27/1000) * 100
print("Percent of records missing weight gained data:", missing_percent)

Percent of records missing weight gained data: 2.7

> The percent of records that are missing: This counts the missing values in the gained column, divides by the total number of records, and multiplies by 100 to get the percentage.

7. Calculate the mean of the variable `weeks` and store it in a new variable.

In [ ]:
weeks_mean = np.mean(ncbirths["weeks"])
weeks_mean

37.17134268537074

8. Create a new column in the dataset `ncbirths` called `week_ave`.  The column `week_ave` should have value "AboveAve" when weeks is greather than or equal to its mean, and have value "BelowAve" when weeks is less than its mean.

In [ ]:
ncbirths['week_ave'] = 'BelowAve'

In [ ]:
week_ave_idx = ncbirths['weeks'] >= weeks_mean
ncbirths.loc[week_ave_idx, 'week_ave'] = 'AboveAve'

In [ ]:
week_ave_counts = ncbirths["week_ave"].value_counts()

In [ ]:
print(week_ave_counts)

week_ave
AboveAve    741
BelowAve    259
Name: count, dtype: int64

9. Create a table for the counts of the values in the new variable `week_ave`.

In [ ]:
week_ave = ncbirths['week_ave'].value_counts()

In [ ]:
print(week_ave)

week_ave
AboveAve    741
BelowAve    259
Name: count, dtype: int64

In [ ]:
print(ncbirths)

     fage  mage       mature  weeks     premie  visits      marital  gained  \
0     NaN    13  younger mom   38.0  full term    10.0      married    38.0
1     NaN    14  younger mom   38.0  full term    15.0      married    20.0
2    19.0    15  younger mom   37.0  full term    11.0      married    38.0
3    21.0    15  younger mom   38.0  full term     6.0      married    34.0
4     NaN    15  younger mom   38.0  full term     9.0      married    27.0
..    ...   ...          ...    ...        ...     ...          ...     ...
995  47.0    42   mature mom   38.0  full term    10.0  not married    26.0
996  34.0    42   mature mom   38.0  full term    18.0  not married    20.0
997  39.0    45   mature mom   38.0  full term    15.0  not married    32.0
998  55.0    46   mature mom   31.0     premie     8.0  not married    25.0
999  45.0    50   mature mom   38.0  full term    14.0  not married    23.0

     weight lowbirthweight  gender      habit   whitemom  missing_gained  \
0      7.63        not low    male  nonsmoker  not white           False
1      7.88        not low    male  nonsmoker  not white           False
2      6.63        not low  female  nonsmoker      white           False
3      8.00        not low    male  nonsmoker      white           False
4      6.38        not low  female  nonsmoker  not white           False
..      ...            ...     ...        ...        ...             ...
995    8.44        not low    male  nonsmoker  not white           False
996    6.19        not low  female  nonsmoker      white           False
997    6.94        not low  female  nonsmoker      white           False
998    4.56            low  female  nonsmoker  not white           False
999    7.13        not low  female  nonsmoker      white           False

     week_ave
0    AboveAve
1    AboveAve
2    BelowAve
3    AboveAve
4    AboveAve
..        ...
995  AboveAve
996  AboveAve
997  AboveAve
998  BelowAve
999  AboveAve

[1000 rows x 15 columns]

## Police Shootings dataset

10. Execute the cell below to download and import the dataset Police Shootings from Dr. Donatello's webpage.  Read about the dataset on the webpage where the Washington Post's hosts the dataset: <https://github.com/washingtonpost/data-police-shootings>.

In [ ]:
police_shootings = pd.read_excel("https://www.norcalbiostat.com/data/fatal-police-shootings-data.xlsx")

11. Create (a new variable that holds) a boolean Series that is True whenever `race` is NA *or* `race` is equal to the letter "O".

In [ ]:
race_na_o = (police_shootings["race"].isna()) | (police_shootings["race"] == "O")

In [ ]:
race_na_o

0       False
1       False
2       False
3       False
4       False
        ...
3955     True
3956    False
3957     True
3958     True
3959     True
Name: race, Length: 3960, dtype: bool

12. Set the values of `race`, where `race` is NA or `race` is "O", equal to the string "unknown".

In [ ]:
police_shootings.loc[race_na_o, "race"] = "unknown"

In [ ]:
police_shootings

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3955,4352,TK TK,2019-01-06,shot,undetermined,NaN,M,unknown,Hurricane,WV,False,undetermined,Car,False
3956,4353,TK TK,2019-01-06,shot,unarmed,NaN,M,B,Portland,OR,True,undetermined,Not fleeing,False
3957,4358,TK TK,2019-01-06,shot,knife,NaN,M,unknown,Glen Valley,CA,False,other,Not fleeing,False
3958,4359,TK TK,2019-01-06,shot,undetermined,NaN,M,unknown,Cache,OK,False,undetermined,Car,False
3959,4351,TK TK,2019-01-07,shot,gun,38.0,M,unknown,Kent,WA,False,attack,Car,False

13. Change the type of the column `race` to type `category`.

In [ ]:
police_shootings["race"] = police_shootings["race"].astype("category")
police_shootings["race"]

0             A
1             W
2             H
3             W
4             H
         ...
3955    unknown
3956          B
3957    unknown
3958    unknown
3959    unknown
Name: race, Length: 3960, dtype: category
Categories (6, object): ['A', 'B', 'H', 'N', 'W', 'unknown']

14. Rename the categories of `race` according as follows:

* "A" -> "asian"
* "B" -> "black"
* "H" -> "hispanic"
* "N" -> "native"
* "W" -> "white"

In [ ]:
race_mapping = {"A": "asian", "B": "black", "H": "hispanic", "N": "native", "W": "white"}
police_shootings["race"] = police_shootings["race"].cat.rename_categories(race_mapping)

In [ ]:
police_shootings["race"]

0          asian
1          white
2       hispanic
3          white
4       hispanic
          ...
3955     unknown
3956       black
3957     unknown
3958     unknown
3959     unknown
Name: race, Length: 3960, dtype: category
Categories (6, object): ['asian', 'black', 'hispanic', 'native', 'white', 'unknown']

15. Create a table for the counts of the values in the variable `race`.

In [ ]:
race_counts = police_shootings["race"].value_counts()

In [ ]:
race_counts

race
white       1825
black        927
hispanic     659
unknown      426
native        62
asian         61
Name: count, dtype: int64

16. Calculate the proportions of the `race`s, relative to the total number of rows in `police_shootings`, that were shot by police in 2015.

In [ ]:
total_shootings_2015 = police_shootings[police_shootings["date"].dt.year == 2015].shape[0]

In [ ]:
race_proportions_2015 = race_counts / total_shootings_2015

In [ ]:
print(race_counts)

race
white       1825
black        927
hispanic     659
unknown      426
native        62
asian         61
Name: count, dtype: int64

In [ ]:
print(race_proportions_2015)

race
white       1.834171
black       0.931658
hispanic    0.662312
unknown     0.428141
native      0.062312
asian       0.061307
Name: count, dtype: float64